print("#######################################")
print("############## Welcome ################")
print("#######################################")
print()
goal = int(input("What is your goal?\n1 - Weight Gain\n2 - Weight Loss\n3 - Weight Maintain\n:"))
weight = int(input("Weight: "))
height = int(input("Height (in Cm): "))
age = int(input("Age: "))
print()
metabolism = 66 + (13.8*weight) + (5*height) - (6.8*age)