print("#######################################")
print("############## Welcome ################")
print("#######################################")
print()
objetivo = int(input("What is your goal?\n1 - Weight Gain\n2 - Weight Loss\n3 - Weight Maintain\n:"))
peso = int(input("Weight: "))
altura = int(input("Height (in Cm): "))
idade = int(input("Age: "))
print()
metabolismo = 66 + (13.8*peso) + (5*altura) - (6.8*idade)